################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
OBJS := 
C++_DEPS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Tools/rcapsdump/src \
Tools/dotXSIConverter/src \
Tools/XSIExport/src \
Tools/XMLConverter/src \
Tools/XMLConverter/CMakeFiles/OgreXMLConverter.dir/src \
Tools/VRMLConverter/vrmllib/src \
Tools/VRMLConverter/src \
Tools/MilkshapeExport/src \
Tools/MeshUpgrader/src \
Tools/MeshUpgrader/CMakeFiles/OgreMeshUpgrader.dir/src \
Tools/MayaExport/src \
Tools/MaterialEditor/wxscintilla_1.69.2/src \
Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src \
Tools/MaterialEditor/MaterialEditor/src \
Tools/LightwaveConverter/src \
Tools/BitmapFontBuilderTool \
Tools/3dsmaxExport/OgreExport/src \
Tools/3dsmaxExport/MaxscriptExport/plugins/PhysiqueInterface_sources \
Tests/src \
Tests/PlayPen/src \
Tests/OgreMain/src \
Tests/Components/Terrain/src \
Tests/Components/Property/src \
Tests/Components/Paging/src \
Tests/CapsReport \
Samples/Water/src \
Samples/Water/CMakeFiles/Sample_Water.dir/src \
Samples/VolumeTex/src \
Samples/VolumeTex/CMakeFiles/Sample_VolumeTex.dir/src \
Samples/Transparency/src \
Samples/Transparency/CMakeFiles/Sample_Transparency.dir/src \
Samples/TextureFX/src \
Samples/TextureFX/CMakeFiles/Sample_TextureFX.dir/src \
Samples/Terrain/src \
Samples/Terrain/CMakeFiles/Sample_Terrain.dir/src \
Samples/SphereMapping/src \
Samples/SphereMapping/CMakeFiles/Sample_SphereMapping.dir/src \
Samples/Smoke/src \
Samples/Smoke/CMakeFiles/Sample_Smoke.dir/src \
Samples/SkyPlane/src \
Samples/SkyPlane/CMakeFiles/Sample_SkyPlane.dir/src \
Samples/SkyDome/src \
Samples/SkyDome/CMakeFiles/Sample_SkyDome.dir/src \
Samples/SkyBox/src \
Samples/SkyBox/CMakeFiles/Sample_SkyBox.dir/src \
Samples/SkeletalAnimation/src \
Samples/SkeletalAnimation/CMakeFiles/Sample_SkeletalAnimation.dir/src \
Samples/Shadows/src \
Samples/Shadows/CMakeFiles/Sample_Shadows.dir/src \
Samples/ShaderSystem/src \
Samples/ShaderSystem/CMakeFiles/Sample_ShaderSystem.dir/src \
Samples/ParticleGS/src \
Samples/ParticleGS/CMakeFiles/Sample_ParticleGS.dir/src \
Samples/ParticleFX/src \
Samples/ParticleFX/CMakeFiles/Sample_ParticleFX.dir/src \
Samples/PCZTestApp/src \
Samples/OceanDemo/src \
Samples/OceanDemo/CMakeFiles/Sample_Ocean.dir/src \
Samples/Media/materials/programs \
Samples/Lighting/src \
Samples/Lighting/CMakeFiles/Sample_Lighting.dir/src \
Samples/Isosurf/src \
Samples/Isosurf/CMakeFiles/Sample_Isosurf.dir/src \
Samples/Instancing/src \
Samples/Instancing/CMakeFiles/Sample_Instancing.dir/src \
Samples/Grass/src \
Samples/Grass/CMakeFiles/Sample_Grass.dir/src \
Samples/Fresnel/src \
Samples/Fresnel/CMakeFiles/Sample_Fresnel.dir/src \
Samples/FacialAnimation/src \
Samples/FacialAnimation/CMakeFiles/Sample_FacialAnimation.dir/src \
Samples/DynTex/src \
Samples/DynTex/CMakeFiles/Sample_DynTex.dir/src \
Samples/Dot3Bump/src \
Samples/Dot3Bump/CMakeFiles/Sample_Dot3Bump.dir/src \
Samples/DeferredShading/src \
Samples/DeferredShading/CMakeFiles/Sample_DeferredShading.dir/src \
Samples/CubeMapping/src \
Samples/CubeMapping/CMakeFiles/Sample_CubeMapping.dir/src \
Samples/Compositor/src \
Samples/Compositor/CMakeFiles/Sample_Compositor.dir/src \
Samples/Character/src \
Samples/Character/CMakeFiles/Sample_Character.dir/src \
Samples/CelShading/src \
Samples/CelShading/CMakeFiles/Sample_CelShading.dir/src \
Samples/CameraTrack/src \
Samples/CameraTrack/CMakeFiles/Sample_CameraTrack.dir/src \
Samples/Browser/src \
Samples/Browser/CMakeFiles/SampleBrowser.dir/src \
Samples/BezierPatch/src \
Samples/BezierPatch/CMakeFiles/Sample_BezierPatch.dir/src \
Samples/BSP/src \
Samples/BSP/CMakeFiles/Sample_BSP.dir/src \
SDK/OSX/Xcode\ Templates/Xcode/Project\ Templates/Ogre/iPhone\ OS/Classes \
SDK/OSX/Xcode\ Templates/Xcode/Project\ Templates/Ogre/Mac\ OS\ X/Classes \
SDK/OSX/Xcode\ Templates/Xcode/File\ Templates/Ogre/Mac\ OS\ X\ FrameListener\ subclass.pbfiletemplate \
SDK/OSX/Xcode\ Templates/Xcode/File\ Templates/Ogre/Mac\ OS\ X\ Application\ class.pbfiletemplate \
RenderSystems/GLES/src \
RenderSystems/GLES/src/EGL/WIN32 \
RenderSystems/GLES/src/EGL/Symbian \
RenderSystems/GLES/src/EGL \
RenderSystems/GLES/src/EGL/GTK \
RenderSystems/GL/src/win32 \
RenderSystems/GL/src/nvparse \
RenderSystems/GL/src/gtk \
RenderSystems/GL/src \
RenderSystems/GL/src/atifs/src \
RenderSystems/GL/src/SDL \
RenderSystems/GL/src/OSX \
RenderSystems/GL/src/GLX \
RenderSystems/GL/src/GLSL/src \
RenderSystems/GL/CMakeFiles/RenderSystem_GL.dir/src/nvparse \
RenderSystems/GL/CMakeFiles/RenderSystem_GL.dir/src \
RenderSystems/GL/CMakeFiles/RenderSystem_GL.dir/src/atifs/src \
RenderSystems/GL/CMakeFiles/RenderSystem_GL.dir/src/GLX \
RenderSystems/GL/CMakeFiles/RenderSystem_GL.dir/src/GLSL/src \
RenderSystems/Direct3D9/src \
RenderSystems/Direct3D11/src \
RenderSystems/Direct3D10/src \
PlugIns/ParticleFX/src \
PlugIns/ParticleFX/CMakeFiles/Plugin_ParticleFX.dir/src \
PlugIns/PCZSceneManager/src \
PlugIns/PCZSceneManager/CMakeFiles/Plugin_PCZSceneManager.dir/src \
PlugIns/OctreeZone/src \
PlugIns/OctreeZone/CMakeFiles/Plugin_OctreeZone.dir/src \
PlugIns/OctreeSceneManager/src \
PlugIns/OctreeSceneManager/CMakeFiles/Plugin_OctreeSceneManager.dir/src \
PlugIns/EXRCodec/src \
PlugIns/CgProgramManager/src \
PlugIns/CgProgramManager/CMakeFiles/Plugin_CgProgramManager.dir/src \
PlugIns/BSPSceneManager/src \
PlugIns/BSPSceneManager/CMakeFiles/Plugin_BSPSceneManager.dir/src \
OgreMain/src/nedmalloc \
OgreMain/src/iPhone \
OgreMain/src/gtk \
OgreMain/src/WIN32 \
OgreMain/src/Threading \
OgreMain/src/Symbian \
OgreMain/src \
OgreMain/src/OSX \
OgreMain/src/GLX \
OgreMain/CMakeFiles/OgreMain.dir/src/Threading \
OgreMain/CMakeFiles/OgreMain.dir/src \
OgreMain/CMakeFiles/OgreMain.dir/src/GLX \
Components/Terrain/src \
Components/Terrain/CMakeFiles/OgreTerrain.dir/src \
Components/RTShaderSystem/src \
Components/RTShaderSystem/CMakeFiles/OgreRTShaderSystem.dir/src \
Components/Property/src \
Components/Property/CMakeFiles/OgreProperty.dir/src \
Components/Paging/src \
Components/Paging/CMakeFiles/OgrePaging.dir/src \
CMakeFiles/CompilerIdCXX \
CMakeFiles/CompilerIdC \
CMake/CMakeFiles/CompilerIdCXX \
CMake/CMakeFiles/CompilerIdC \

