################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CXX_SRCS += \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/AutoComplete.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/CallTip.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/CellBuffer.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/CharClassify.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ContractionState.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Document.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/DocumentAccessor.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Editor.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ExternalLexer.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Indicator.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/KeyMap.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/KeyWords.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAPDL.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAU3.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAVE.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAda.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAsm.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAsn1.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBaan.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBash.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBasic.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBullant.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCLW.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCPP.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCSS.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCaml.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexConf.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCrontab.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCsound.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexEScript.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexEiffel.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexErlang.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexFlagship.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexForth.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexFortran.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexGui4Cli.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexHTML.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexHaskell.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexInno.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexKix.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexLisp.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexLout.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexLua.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMMIXAL.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMPT.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMSSQL.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMatlab.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMetapost.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexNsis.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexOMS.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexOpal.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexOthers.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPB.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPOV.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPS.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPascal.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPerl.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPython.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexRebol.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexRuby.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSQL.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexScriptol.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSmalltalk.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSpecman.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSpice.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexTADS3.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexTCL.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexTeX.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexVB.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexVHDL.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexVerilog.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexYAML.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LineMarker.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/PropSet.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/RESearch.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ScintillaBase.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Style.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/StyleContext.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/UniConversion.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ViewStyle.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/WindowAccessor.cxx \
../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/XPM.cxx 

OBJS += \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/AutoComplete.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/CallTip.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/CellBuffer.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/CharClassify.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ContractionState.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Document.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/DocumentAccessor.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Editor.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ExternalLexer.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Indicator.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/KeyMap.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/KeyWords.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAPDL.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAU3.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAVE.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAda.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAsm.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAsn1.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBaan.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBash.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBasic.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBullant.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCLW.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCPP.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCSS.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCaml.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexConf.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCrontab.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCsound.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexEScript.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexEiffel.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexErlang.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexFlagship.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexForth.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexFortran.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexGui4Cli.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexHTML.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexHaskell.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexInno.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexKix.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexLisp.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexLout.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexLua.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMMIXAL.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMPT.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMSSQL.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMatlab.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMetapost.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexNsis.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexOMS.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexOpal.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexOthers.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPB.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPOV.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPS.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPascal.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPerl.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPython.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexRebol.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexRuby.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSQL.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexScriptol.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSmalltalk.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSpecman.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSpice.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexTADS3.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexTCL.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexTeX.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexVB.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexVHDL.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexVerilog.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexYAML.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LineMarker.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/PropSet.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/RESearch.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ScintillaBase.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Style.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/StyleContext.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/UniConversion.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ViewStyle.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/WindowAccessor.o \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/XPM.o 

CXX_DEPS += \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/AutoComplete.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/CallTip.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/CellBuffer.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/CharClassify.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ContractionState.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Document.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/DocumentAccessor.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Editor.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ExternalLexer.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Indicator.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/KeyMap.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/KeyWords.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAPDL.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAU3.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAVE.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAda.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAsm.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexAsn1.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBaan.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBash.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBasic.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexBullant.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCLW.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCPP.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCSS.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCaml.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexConf.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCrontab.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexCsound.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexEScript.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexEiffel.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexErlang.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexFlagship.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexForth.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexFortran.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexGui4Cli.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexHTML.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexHaskell.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexInno.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexKix.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexLisp.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexLout.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexLua.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMMIXAL.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMPT.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMSSQL.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMatlab.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexMetapost.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexNsis.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexOMS.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexOpal.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexOthers.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPB.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPOV.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPS.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPascal.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPerl.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexPython.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexRebol.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexRuby.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSQL.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexScriptol.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSmalltalk.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSpecman.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexSpice.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexTADS3.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexTCL.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexTeX.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexVB.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexVHDL.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexVerilog.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LexYAML.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/LineMarker.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/PropSet.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/RESearch.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ScintillaBase.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/Style.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/StyleContext.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/UniConversion.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/ViewStyle.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/WindowAccessor.d \
./Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/XPM.d 


# Each subdirectory must supply rules for building sources it contributes
Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/%.o: ../Tools/MaterialEditor/wxscintilla_1.69.2/src/scintilla/src/%.cxx
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -DUSE_GLUT -DXN_SSE -I/usr/include/ni -I/usr/lib -I/usr/include/ni/Linux-x86 -I/usr/include/nite -I/usr/include/OGRE -I/usr/include/OIS -O0 -g3 -Wall -msse3 -mssse3  -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


