# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/kinect/LAB/Eclipse/ImportSinbad

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/kinect/LAB/Eclipse/TuxSimbad

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /opt/kinect/LAB/Eclipse/TuxSimbad/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/kinect/LAB/Eclipse/TuxSimbad/CMakeFiles /opt/kinect/LAB/Eclipse/TuxSimbad/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/kinect/LAB/Eclipse/TuxSimbad/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OgreMain

# Build rule for target.
OgreMain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OgreMain
.PHONY : OgreMain

# fast build rule for target.
OgreMain/fast:
	$(MAKE) -f OgreMain/CMakeFiles/OgreMain.dir/build.make OgreMain/CMakeFiles/OgreMain.dir/build
.PHONY : OgreMain/fast

#=============================================================================
# Target rules for targets named RenderSystem_GL

# Build rule for target.
RenderSystem_GL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RenderSystem_GL
.PHONY : RenderSystem_GL

# fast build rule for target.
RenderSystem_GL/fast:
	$(MAKE) -f RenderSystems/GL/CMakeFiles/RenderSystem_GL.dir/build.make RenderSystems/GL/CMakeFiles/RenderSystem_GL.dir/build
.PHONY : RenderSystem_GL/fast

#=============================================================================
# Target rules for targets named Plugin_OctreeSceneManager

# Build rule for target.
Plugin_OctreeSceneManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Plugin_OctreeSceneManager
.PHONY : Plugin_OctreeSceneManager

# fast build rule for target.
Plugin_OctreeSceneManager/fast:
	$(MAKE) -f PlugIns/OctreeSceneManager/CMakeFiles/Plugin_OctreeSceneManager.dir/build.make PlugIns/OctreeSceneManager/CMakeFiles/Plugin_OctreeSceneManager.dir/build
.PHONY : Plugin_OctreeSceneManager/fast

#=============================================================================
# Target rules for targets named Plugin_BSPSceneManager

# Build rule for target.
Plugin_BSPSceneManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Plugin_BSPSceneManager
.PHONY : Plugin_BSPSceneManager

# fast build rule for target.
Plugin_BSPSceneManager/fast:
	$(MAKE) -f PlugIns/BSPSceneManager/CMakeFiles/Plugin_BSPSceneManager.dir/build.make PlugIns/BSPSceneManager/CMakeFiles/Plugin_BSPSceneManager.dir/build
.PHONY : Plugin_BSPSceneManager/fast

#=============================================================================
# Target rules for targets named Plugin_CgProgramManager

# Build rule for target.
Plugin_CgProgramManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Plugin_CgProgramManager
.PHONY : Plugin_CgProgramManager

# fast build rule for target.
Plugin_CgProgramManager/fast:
	$(MAKE) -f PlugIns/CgProgramManager/CMakeFiles/Plugin_CgProgramManager.dir/build.make PlugIns/CgProgramManager/CMakeFiles/Plugin_CgProgramManager.dir/build
.PHONY : Plugin_CgProgramManager/fast

#=============================================================================
# Target rules for targets named Plugin_ParticleFX

# Build rule for target.
Plugin_ParticleFX: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Plugin_ParticleFX
.PHONY : Plugin_ParticleFX

# fast build rule for target.
Plugin_ParticleFX/fast:
	$(MAKE) -f PlugIns/ParticleFX/CMakeFiles/Plugin_ParticleFX.dir/build.make PlugIns/ParticleFX/CMakeFiles/Plugin_ParticleFX.dir/build
.PHONY : Plugin_ParticleFX/fast

#=============================================================================
# Target rules for targets named Plugin_PCZSceneManager

# Build rule for target.
Plugin_PCZSceneManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Plugin_PCZSceneManager
.PHONY : Plugin_PCZSceneManager

# fast build rule for target.
Plugin_PCZSceneManager/fast:
	$(MAKE) -f PlugIns/PCZSceneManager/CMakeFiles/Plugin_PCZSceneManager.dir/build.make PlugIns/PCZSceneManager/CMakeFiles/Plugin_PCZSceneManager.dir/build
.PHONY : Plugin_PCZSceneManager/fast

#=============================================================================
# Target rules for targets named Plugin_OctreeZone

# Build rule for target.
Plugin_OctreeZone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Plugin_OctreeZone
.PHONY : Plugin_OctreeZone

# fast build rule for target.
Plugin_OctreeZone/fast:
	$(MAKE) -f PlugIns/OctreeZone/CMakeFiles/Plugin_OctreeZone.dir/build.make PlugIns/OctreeZone/CMakeFiles/Plugin_OctreeZone.dir/build
.PHONY : Plugin_OctreeZone/fast

#=============================================================================
# Target rules for targets named OgrePaging

# Build rule for target.
OgrePaging: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OgrePaging
.PHONY : OgrePaging

# fast build rule for target.
OgrePaging/fast:
	$(MAKE) -f Components/Paging/CMakeFiles/OgrePaging.dir/build.make Components/Paging/CMakeFiles/OgrePaging.dir/build
.PHONY : OgrePaging/fast

#=============================================================================
# Target rules for targets named OgreProperty

# Build rule for target.
OgreProperty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OgreProperty
.PHONY : OgreProperty

# fast build rule for target.
OgreProperty/fast:
	$(MAKE) -f Components/Property/CMakeFiles/OgreProperty.dir/build.make Components/Property/CMakeFiles/OgreProperty.dir/build
.PHONY : OgreProperty/fast

#=============================================================================
# Target rules for targets named OgreTerrain

# Build rule for target.
OgreTerrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OgreTerrain
.PHONY : OgreTerrain

# fast build rule for target.
OgreTerrain/fast:
	$(MAKE) -f Components/Terrain/CMakeFiles/OgreTerrain.dir/build.make Components/Terrain/CMakeFiles/OgreTerrain.dir/build
.PHONY : OgreTerrain/fast

#=============================================================================
# Target rules for targets named OgreRTShaderSystem

# Build rule for target.
OgreRTShaderSystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OgreRTShaderSystem
.PHONY : OgreRTShaderSystem

# fast build rule for target.
OgreRTShaderSystem/fast:
	$(MAKE) -f Components/RTShaderSystem/CMakeFiles/OgreRTShaderSystem.dir/build.make Components/RTShaderSystem/CMakeFiles/OgreRTShaderSystem.dir/build
.PHONY : OgreRTShaderSystem/fast

#=============================================================================
# Target rules for targets named Sample_BezierPatch

# Build rule for target.
Sample_BezierPatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_BezierPatch
.PHONY : Sample_BezierPatch

# fast build rule for target.
Sample_BezierPatch/fast:
	$(MAKE) -f Samples/BezierPatch/CMakeFiles/Sample_BezierPatch.dir/build.make Samples/BezierPatch/CMakeFiles/Sample_BezierPatch.dir/build
.PHONY : Sample_BezierPatch/fast

#=============================================================================
# Target rules for targets named Sample_CameraTrack

# Build rule for target.
Sample_CameraTrack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_CameraTrack
.PHONY : Sample_CameraTrack

# fast build rule for target.
Sample_CameraTrack/fast:
	$(MAKE) -f Samples/CameraTrack/CMakeFiles/Sample_CameraTrack.dir/build.make Samples/CameraTrack/CMakeFiles/Sample_CameraTrack.dir/build
.PHONY : Sample_CameraTrack/fast

#=============================================================================
# Target rules for targets named Sample_Character

# Build rule for target.
Sample_Character: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Character
.PHONY : Sample_Character

# fast build rule for target.
Sample_Character/fast:
	$(MAKE) -f Samples/Character/CMakeFiles/Sample_Character.dir/build.make Samples/Character/CMakeFiles/Sample_Character.dir/build
.PHONY : Sample_Character/fast

#=============================================================================
# Target rules for targets named Sample_Compositor

# Build rule for target.
Sample_Compositor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Compositor
.PHONY : Sample_Compositor

# fast build rule for target.
Sample_Compositor/fast:
	$(MAKE) -f Samples/Compositor/CMakeFiles/Sample_Compositor.dir/build.make Samples/Compositor/CMakeFiles/Sample_Compositor.dir/build
.PHONY : Sample_Compositor/fast

#=============================================================================
# Target rules for targets named Sample_FacialAnimation

# Build rule for target.
Sample_FacialAnimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_FacialAnimation
.PHONY : Sample_FacialAnimation

# fast build rule for target.
Sample_FacialAnimation/fast:
	$(MAKE) -f Samples/FacialAnimation/CMakeFiles/Sample_FacialAnimation.dir/build.make Samples/FacialAnimation/CMakeFiles/Sample_FacialAnimation.dir/build
.PHONY : Sample_FacialAnimation/fast

#=============================================================================
# Target rules for targets named Sample_Grass

# Build rule for target.
Sample_Grass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Grass
.PHONY : Sample_Grass

# fast build rule for target.
Sample_Grass/fast:
	$(MAKE) -f Samples/Grass/CMakeFiles/Sample_Grass.dir/build.make Samples/Grass/CMakeFiles/Sample_Grass.dir/build
.PHONY : Sample_Grass/fast

#=============================================================================
# Target rules for targets named Sample_Instancing

# Build rule for target.
Sample_Instancing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Instancing
.PHONY : Sample_Instancing

# fast build rule for target.
Sample_Instancing/fast:
	$(MAKE) -f Samples/Instancing/CMakeFiles/Sample_Instancing.dir/build.make Samples/Instancing/CMakeFiles/Sample_Instancing.dir/build
.PHONY : Sample_Instancing/fast

#=============================================================================
# Target rules for targets named Sample_Lighting

# Build rule for target.
Sample_Lighting: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Lighting
.PHONY : Sample_Lighting

# fast build rule for target.
Sample_Lighting/fast:
	$(MAKE) -f Samples/Lighting/CMakeFiles/Sample_Lighting.dir/build.make Samples/Lighting/CMakeFiles/Sample_Lighting.dir/build
.PHONY : Sample_Lighting/fast

#=============================================================================
# Target rules for targets named Sample_Ocean

# Build rule for target.
Sample_Ocean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Ocean
.PHONY : Sample_Ocean

# fast build rule for target.
Sample_Ocean/fast:
	$(MAKE) -f Samples/OceanDemo/CMakeFiles/Sample_Ocean.dir/build.make Samples/OceanDemo/CMakeFiles/Sample_Ocean.dir/build
.PHONY : Sample_Ocean/fast

#=============================================================================
# Target rules for targets named Sample_ParticleFX

# Build rule for target.
Sample_ParticleFX: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_ParticleFX
.PHONY : Sample_ParticleFX

# fast build rule for target.
Sample_ParticleFX/fast:
	$(MAKE) -f Samples/ParticleFX/CMakeFiles/Sample_ParticleFX.dir/build.make Samples/ParticleFX/CMakeFiles/Sample_ParticleFX.dir/build
.PHONY : Sample_ParticleFX/fast

#=============================================================================
# Target rules for targets named Sample_ShaderSystem

# Build rule for target.
Sample_ShaderSystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_ShaderSystem
.PHONY : Sample_ShaderSystem

# fast build rule for target.
Sample_ShaderSystem/fast:
	$(MAKE) -f Samples/ShaderSystem/CMakeFiles/Sample_ShaderSystem.dir/build.make Samples/ShaderSystem/CMakeFiles/Sample_ShaderSystem.dir/build
.PHONY : Sample_ShaderSystem/fast

#=============================================================================
# Target rules for targets named Sample_Shadows

# Build rule for target.
Sample_Shadows: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Shadows
.PHONY : Sample_Shadows

# fast build rule for target.
Sample_Shadows/fast:
	$(MAKE) -f Samples/Shadows/CMakeFiles/Sample_Shadows.dir/build.make Samples/Shadows/CMakeFiles/Sample_Shadows.dir/build
.PHONY : Sample_Shadows/fast

#=============================================================================
# Target rules for targets named Sample_SkeletalAnimation

# Build rule for target.
Sample_SkeletalAnimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_SkeletalAnimation
.PHONY : Sample_SkeletalAnimation

# fast build rule for target.
Sample_SkeletalAnimation/fast:
	$(MAKE) -f Samples/SkeletalAnimation/CMakeFiles/Sample_SkeletalAnimation.dir/build.make Samples/SkeletalAnimation/CMakeFiles/Sample_SkeletalAnimation.dir/build
.PHONY : Sample_SkeletalAnimation/fast

#=============================================================================
# Target rules for targets named Sample_SkyBox

# Build rule for target.
Sample_SkyBox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_SkyBox
.PHONY : Sample_SkyBox

# fast build rule for target.
Sample_SkyBox/fast:
	$(MAKE) -f Samples/SkyBox/CMakeFiles/Sample_SkyBox.dir/build.make Samples/SkyBox/CMakeFiles/Sample_SkyBox.dir/build
.PHONY : Sample_SkyBox/fast

#=============================================================================
# Target rules for targets named Sample_SkyDome

# Build rule for target.
Sample_SkyDome: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_SkyDome
.PHONY : Sample_SkyDome

# fast build rule for target.
Sample_SkyDome/fast:
	$(MAKE) -f Samples/SkyDome/CMakeFiles/Sample_SkyDome.dir/build.make Samples/SkyDome/CMakeFiles/Sample_SkyDome.dir/build
.PHONY : Sample_SkyDome/fast

#=============================================================================
# Target rules for targets named Sample_SkyPlane

# Build rule for target.
Sample_SkyPlane: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_SkyPlane
.PHONY : Sample_SkyPlane

# fast build rule for target.
Sample_SkyPlane/fast:
	$(MAKE) -f Samples/SkyPlane/CMakeFiles/Sample_SkyPlane.dir/build.make Samples/SkyPlane/CMakeFiles/Sample_SkyPlane.dir/build
.PHONY : Sample_SkyPlane/fast

#=============================================================================
# Target rules for targets named Sample_Smoke

# Build rule for target.
Sample_Smoke: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Smoke
.PHONY : Sample_Smoke

# fast build rule for target.
Sample_Smoke/fast:
	$(MAKE) -f Samples/Smoke/CMakeFiles/Sample_Smoke.dir/build.make Samples/Smoke/CMakeFiles/Sample_Smoke.dir/build
.PHONY : Sample_Smoke/fast

#=============================================================================
# Target rules for targets named Sample_SphereMapping

# Build rule for target.
Sample_SphereMapping: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_SphereMapping
.PHONY : Sample_SphereMapping

# fast build rule for target.
Sample_SphereMapping/fast:
	$(MAKE) -f Samples/SphereMapping/CMakeFiles/Sample_SphereMapping.dir/build.make Samples/SphereMapping/CMakeFiles/Sample_SphereMapping.dir/build
.PHONY : Sample_SphereMapping/fast

#=============================================================================
# Target rules for targets named Sample_Terrain

# Build rule for target.
Sample_Terrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Terrain
.PHONY : Sample_Terrain

# fast build rule for target.
Sample_Terrain/fast:
	$(MAKE) -f Samples/Terrain/CMakeFiles/Sample_Terrain.dir/build.make Samples/Terrain/CMakeFiles/Sample_Terrain.dir/build
.PHONY : Sample_Terrain/fast

#=============================================================================
# Target rules for targets named Sample_TextureFX

# Build rule for target.
Sample_TextureFX: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_TextureFX
.PHONY : Sample_TextureFX

# fast build rule for target.
Sample_TextureFX/fast:
	$(MAKE) -f Samples/TextureFX/CMakeFiles/Sample_TextureFX.dir/build.make Samples/TextureFX/CMakeFiles/Sample_TextureFX.dir/build
.PHONY : Sample_TextureFX/fast

#=============================================================================
# Target rules for targets named Sample_Transparency

# Build rule for target.
Sample_Transparency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Transparency
.PHONY : Sample_Transparency

# fast build rule for target.
Sample_Transparency/fast:
	$(MAKE) -f Samples/Transparency/CMakeFiles/Sample_Transparency.dir/build.make Samples/Transparency/CMakeFiles/Sample_Transparency.dir/build
.PHONY : Sample_Transparency/fast

#=============================================================================
# Target rules for targets named Sample_VolumeTex

# Build rule for target.
Sample_VolumeTex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_VolumeTex
.PHONY : Sample_VolumeTex

# fast build rule for target.
Sample_VolumeTex/fast:
	$(MAKE) -f Samples/VolumeTex/CMakeFiles/Sample_VolumeTex.dir/build.make Samples/VolumeTex/CMakeFiles/Sample_VolumeTex.dir/build
.PHONY : Sample_VolumeTex/fast

#=============================================================================
# Target rules for targets named Sample_Water

# Build rule for target.
Sample_Water: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Water
.PHONY : Sample_Water

# fast build rule for target.
Sample_Water/fast:
	$(MAKE) -f Samples/Water/CMakeFiles/Sample_Water.dir/build.make Samples/Water/CMakeFiles/Sample_Water.dir/build
.PHONY : Sample_Water/fast

#=============================================================================
# Target rules for targets named Sample_BSP

# Build rule for target.
Sample_BSP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_BSP
.PHONY : Sample_BSP

# fast build rule for target.
Sample_BSP/fast:
	$(MAKE) -f Samples/BSP/CMakeFiles/Sample_BSP.dir/build.make Samples/BSP/CMakeFiles/Sample_BSP.dir/build
.PHONY : Sample_BSP/fast

#=============================================================================
# Target rules for targets named Sample_CelShading

# Build rule for target.
Sample_CelShading: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_CelShading
.PHONY : Sample_CelShading

# fast build rule for target.
Sample_CelShading/fast:
	$(MAKE) -f Samples/CelShading/CMakeFiles/Sample_CelShading.dir/build.make Samples/CelShading/CMakeFiles/Sample_CelShading.dir/build
.PHONY : Sample_CelShading/fast

#=============================================================================
# Target rules for targets named Sample_DeferredShading

# Build rule for target.
Sample_DeferredShading: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_DeferredShading
.PHONY : Sample_DeferredShading

# fast build rule for target.
Sample_DeferredShading/fast:
	$(MAKE) -f Samples/DeferredShading/CMakeFiles/Sample_DeferredShading.dir/build.make Samples/DeferredShading/CMakeFiles/Sample_DeferredShading.dir/build
.PHONY : Sample_DeferredShading/fast

#=============================================================================
# Target rules for targets named Sample_CubeMapping

# Build rule for target.
Sample_CubeMapping: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_CubeMapping
.PHONY : Sample_CubeMapping

# fast build rule for target.
Sample_CubeMapping/fast:
	$(MAKE) -f Samples/CubeMapping/CMakeFiles/Sample_CubeMapping.dir/build.make Samples/CubeMapping/CMakeFiles/Sample_CubeMapping.dir/build
.PHONY : Sample_CubeMapping/fast

#=============================================================================
# Target rules for targets named Sample_Dot3Bump

# Build rule for target.
Sample_Dot3Bump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Dot3Bump
.PHONY : Sample_Dot3Bump

# fast build rule for target.
Sample_Dot3Bump/fast:
	$(MAKE) -f Samples/Dot3Bump/CMakeFiles/Sample_Dot3Bump.dir/build.make Samples/Dot3Bump/CMakeFiles/Sample_Dot3Bump.dir/build
.PHONY : Sample_Dot3Bump/fast

#=============================================================================
# Target rules for targets named Sample_DynTex

# Build rule for target.
Sample_DynTex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_DynTex
.PHONY : Sample_DynTex

# fast build rule for target.
Sample_DynTex/fast:
	$(MAKE) -f Samples/DynTex/CMakeFiles/Sample_DynTex.dir/build.make Samples/DynTex/CMakeFiles/Sample_DynTex.dir/build
.PHONY : Sample_DynTex/fast

#=============================================================================
# Target rules for targets named Sample_Fresnel

# Build rule for target.
Sample_Fresnel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Fresnel
.PHONY : Sample_Fresnel

# fast build rule for target.
Sample_Fresnel/fast:
	$(MAKE) -f Samples/Fresnel/CMakeFiles/Sample_Fresnel.dir/build.make Samples/Fresnel/CMakeFiles/Sample_Fresnel.dir/build
.PHONY : Sample_Fresnel/fast

#=============================================================================
# Target rules for targets named Sample_Isosurf

# Build rule for target.
Sample_Isosurf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_Isosurf
.PHONY : Sample_Isosurf

# fast build rule for target.
Sample_Isosurf/fast:
	$(MAKE) -f Samples/Isosurf/CMakeFiles/Sample_Isosurf.dir/build.make Samples/Isosurf/CMakeFiles/Sample_Isosurf.dir/build
.PHONY : Sample_Isosurf/fast

#=============================================================================
# Target rules for targets named Sample_ParticleGS

# Build rule for target.
Sample_ParticleGS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample_ParticleGS
.PHONY : Sample_ParticleGS

# fast build rule for target.
Sample_ParticleGS/fast:
	$(MAKE) -f Samples/ParticleGS/CMakeFiles/Sample_ParticleGS.dir/build.make Samples/ParticleGS/CMakeFiles/Sample_ParticleGS.dir/build
.PHONY : Sample_ParticleGS/fast

#=============================================================================
# Target rules for targets named SampleBrowser

# Build rule for target.
SampleBrowser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SampleBrowser
.PHONY : SampleBrowser

# fast build rule for target.
SampleBrowser/fast:
	$(MAKE) -f Samples/Browser/CMakeFiles/SampleBrowser.dir/build.make Samples/Browser/CMakeFiles/SampleBrowser.dir/build
.PHONY : SampleBrowser/fast

#=============================================================================
# Target rules for targets named OgreXMLConverter

# Build rule for target.
OgreXMLConverter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OgreXMLConverter
.PHONY : OgreXMLConverter

# fast build rule for target.
OgreXMLConverter/fast:
	$(MAKE) -f Tools/XMLConverter/CMakeFiles/OgreXMLConverter.dir/build.make Tools/XMLConverter/CMakeFiles/OgreXMLConverter.dir/build
.PHONY : OgreXMLConverter/fast

#=============================================================================
# Target rules for targets named OgreMeshUpgrader

# Build rule for target.
OgreMeshUpgrader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OgreMeshUpgrader
.PHONY : OgreMeshUpgrader

# fast build rule for target.
OgreMeshUpgrader/fast:
	$(MAKE) -f Tools/MeshUpgrader/CMakeFiles/OgreMeshUpgrader.dir/build.make Tools/MeshUpgrader/CMakeFiles/OgreMeshUpgrader.dir/build
.PHONY : OgreMeshUpgrader/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f Docs/CMakeFiles/doc.dir/build.make Docs/CMakeFiles/doc.dir/build
.PHONY : doc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... OgreMain"
	@echo "... RenderSystem_GL"
	@echo "... Plugin_OctreeSceneManager"
	@echo "... Plugin_BSPSceneManager"
	@echo "... Plugin_CgProgramManager"
	@echo "... Plugin_ParticleFX"
	@echo "... Plugin_PCZSceneManager"
	@echo "... Plugin_OctreeZone"
	@echo "... OgrePaging"
	@echo "... OgreProperty"
	@echo "... OgreTerrain"
	@echo "... OgreRTShaderSystem"
	@echo "... Sample_BezierPatch"
	@echo "... Sample_CameraTrack"
	@echo "... Sample_Character"
	@echo "... Sample_Compositor"
	@echo "... Sample_FacialAnimation"
	@echo "... Sample_Grass"
	@echo "... Sample_Instancing"
	@echo "... Sample_Lighting"
	@echo "... Sample_Ocean"
	@echo "... Sample_ParticleFX"
	@echo "... Sample_ShaderSystem"
	@echo "... Sample_Shadows"
	@echo "... Sample_SkeletalAnimation"
	@echo "... Sample_SkyBox"
	@echo "... Sample_SkyDome"
	@echo "... Sample_SkyPlane"
	@echo "... Sample_Smoke"
	@echo "... Sample_SphereMapping"
	@echo "... Sample_Terrain"
	@echo "... Sample_TextureFX"
	@echo "... Sample_Transparency"
	@echo "... Sample_VolumeTex"
	@echo "... Sample_Water"
	@echo "... Sample_BSP"
	@echo "... Sample_CelShading"
	@echo "... Sample_DeferredShading"
	@echo "... Sample_CubeMapping"
	@echo "... Sample_Dot3Bump"
	@echo "... Sample_DynTex"
	@echo "... Sample_Fresnel"
	@echo "... Sample_Isosurf"
	@echo "... Sample_ParticleGS"
	@echo "... SampleBrowser"
	@echo "... OgreXMLConverter"
	@echo "... OgreMeshUpgrader"
	@echo "... doc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

