################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../OgreMain/src/OgreAlignedAllocator.cpp \
../OgreMain/src/OgreAnimable.cpp \
../OgreMain/src/OgreAnimation.cpp \
../OgreMain/src/OgreAnimationState.cpp \
../OgreMain/src/OgreAnimationTrack.cpp \
../OgreMain/src/OgreArchiveManager.cpp \
../OgreMain/src/OgreAutoParamDataSource.cpp \
../OgreMain/src/OgreAxisAlignedBox.cpp \
../OgreMain/src/OgreBillboard.cpp \
../OgreMain/src/OgreBillboardChain.cpp \
../OgreMain/src/OgreBillboardParticleRenderer.cpp \
../OgreMain/src/OgreBillboardSet.cpp \
../OgreMain/src/OgreBone.cpp \
../OgreMain/src/OgreBorderPanelOverlayElement.cpp \
../OgreMain/src/OgreCamera.cpp \
../OgreMain/src/OgreCodec.cpp \
../OgreMain/src/OgreColourValue.cpp \
../OgreMain/src/OgreCommon.cpp \
../OgreMain/src/OgreCompositionPass.cpp \
../OgreMain/src/OgreCompositionTargetPass.cpp \
../OgreMain/src/OgreCompositionTechnique.cpp \
../OgreMain/src/OgreCompositor.cpp \
../OgreMain/src/OgreCompositorChain.cpp \
../OgreMain/src/OgreCompositorInstance.cpp \
../OgreMain/src/OgreCompositorManager.cpp \
../OgreMain/src/OgreConfigFile.cpp \
../OgreMain/src/OgreControllerManager.cpp \
../OgreMain/src/OgreConvexBody.cpp \
../OgreMain/src/OgreDDSCodec.cpp \
../OgreMain/src/OgreDataStream.cpp \
../OgreMain/src/OgreDefaultHardwareBufferManager.cpp \
../OgreMain/src/OgreDefaultSceneQueries.cpp \
../OgreMain/src/OgreDistanceLodStrategy.cpp \
../OgreMain/src/OgreDynLib.cpp \
../OgreMain/src/OgreDynLibManager.cpp \
../OgreMain/src/OgreEdgeListBuilder.cpp \
../OgreMain/src/OgreEntity.cpp \
../OgreMain/src/OgreException.cpp \
../OgreMain/src/OgreExternalTextureSource.cpp \
../OgreMain/src/OgreExternalTextureSourceManager.cpp \
../OgreMain/src/OgreFileSystem.cpp \
../OgreMain/src/OgreFont.cpp \
../OgreMain/src/OgreFontManager.cpp \
../OgreMain/src/OgreFreeImageCodec.cpp \
../OgreMain/src/OgreFrustum.cpp \
../OgreMain/src/OgreGpuProgram.cpp \
../OgreMain/src/OgreGpuProgramManager.cpp \
../OgreMain/src/OgreGpuProgramParams.cpp \
../OgreMain/src/OgreGpuProgramUsage.cpp \
../OgreMain/src/OgreHardwareBufferManager.cpp \
../OgreMain/src/OgreHardwareIndexBuffer.cpp \
../OgreMain/src/OgreHardwareOcclusionQuery.cpp \
../OgreMain/src/OgreHardwarePixelBuffer.cpp \
../OgreMain/src/OgreHardwareVertexBuffer.cpp \
../OgreMain/src/OgreHighLevelGpuProgram.cpp \
../OgreMain/src/OgreHighLevelGpuProgramManager.cpp \
../OgreMain/src/OgreILCodecs.cpp \
../OgreMain/src/OgreILImageCodec.cpp \
../OgreMain/src/OgreILUtil.cpp \
../OgreMain/src/OgreImage.cpp \
../OgreMain/src/OgreInstancedGeometry.cpp \
../OgreMain/src/OgreKeyFrame.cpp \
../OgreMain/src/OgreLight.cpp \
../OgreMain/src/OgreLodStrategy.cpp \
../OgreMain/src/OgreLodStrategyManager.cpp \
../OgreMain/src/OgreLog.cpp \
../OgreMain/src/OgreLogManager.cpp \
../OgreMain/src/OgreManualObject.cpp \
../OgreMain/src/OgreMaterial.cpp \
../OgreMain/src/OgreMaterialManager.cpp \
../OgreMain/src/OgreMaterialSerializer.cpp \
../OgreMain/src/OgreMath.cpp \
../OgreMain/src/OgreMatrix3.cpp \
../OgreMain/src/OgreMatrix4.cpp \
../OgreMain/src/OgreMemoryAllocatedObject.cpp \
../OgreMain/src/OgreMemoryNedAlloc.cpp \
../OgreMain/src/OgreMemoryNedPooling.cpp \
../OgreMain/src/OgreMemoryTracker.cpp \
../OgreMain/src/OgreMesh.cpp \
../OgreMain/src/OgreMeshManager.cpp \
../OgreMain/src/OgreMeshSerializer.cpp \
../OgreMain/src/OgreMeshSerializerImpl.cpp \
../OgreMain/src/OgreMovableObject.cpp \
../OgreMain/src/OgreMovablePlane.cpp \
../OgreMain/src/OgreNode.cpp \
../OgreMain/src/OgreNumerics.cpp \
../OgreMain/src/OgreOptimisedUtil.cpp \
../OgreMain/src/OgreOptimisedUtilGeneral.cpp \
../OgreMain/src/OgreOptimisedUtilSSE.cpp \
../OgreMain/src/OgreOverlay.cpp \
../OgreMain/src/OgreOverlayContainer.cpp \
../OgreMain/src/OgreOverlayElement.cpp \
../OgreMain/src/OgreOverlayElementCommands.cpp \
../OgreMain/src/OgreOverlayElementFactory.cpp \
../OgreMain/src/OgreOverlayManager.cpp \
../OgreMain/src/OgrePVRTCCodec.cpp \
../OgreMain/src/OgrePanelOverlayElement.cpp \
../OgreMain/src/OgreParticle.cpp \
../OgreMain/src/OgreParticleEmitter.cpp \
../OgreMain/src/OgreParticleEmitterCommands.cpp \
../OgreMain/src/OgreParticleIterator.cpp \
../OgreMain/src/OgreParticleScriptCompiler.cpp \
../OgreMain/src/OgreParticleSystem.cpp \
../OgreMain/src/OgreParticleSystemManager.cpp \
../OgreMain/src/OgrePass.cpp \
../OgreMain/src/OgrePatchMesh.cpp \
../OgreMain/src/OgrePatchSurface.cpp \
../OgreMain/src/OgrePixelCountLodStrategy.cpp \
../OgreMain/src/OgrePixelFormat.cpp \
../OgreMain/src/OgrePlane.cpp \
../OgreMain/src/OgrePlatformInformation.cpp \
../OgreMain/src/OgrePolygon.cpp \
../OgreMain/src/OgrePose.cpp \
../OgreMain/src/OgrePrecompiledHeaders.cpp \
../OgreMain/src/OgrePredefinedControllers.cpp \
../OgreMain/src/OgrePrefabFactory.cpp \
../OgreMain/src/OgreProfiler.cpp \
../OgreMain/src/OgreProgressiveMesh.cpp \
../OgreMain/src/OgreQuaternion.cpp \
../OgreMain/src/OgreRectangle2D.cpp \
../OgreMain/src/OgreRenderQueue.cpp \
../OgreMain/src/OgreRenderQueueInvocation.cpp \
../OgreMain/src/OgreRenderQueueSortingGrouping.cpp \
../OgreMain/src/OgreRenderSystem.cpp \
../OgreMain/src/OgreRenderSystemCapabilities.cpp \
../OgreMain/src/OgreRenderSystemCapabilitiesManager.cpp \
../OgreMain/src/OgreRenderSystemCapabilitiesSerializer.cpp \
../OgreMain/src/OgreRenderTarget.cpp \
../OgreMain/src/OgreRenderTexture.cpp \
../OgreMain/src/OgreRenderToVertexBuffer.cpp \
../OgreMain/src/OgreRenderWindow.cpp \
../OgreMain/src/OgreResource.cpp \
../OgreMain/src/OgreResourceBackgroundQueue.cpp \
../OgreMain/src/OgreResourceGroupManager.cpp \
../OgreMain/src/OgreResourceManager.cpp \
../OgreMain/src/OgreRibbonTrail.cpp \
../OgreMain/src/OgreRoot.cpp \
../OgreMain/src/OgreRotationSpline.cpp \
../OgreMain/src/OgreSceneManager.cpp \
../OgreMain/src/OgreSceneManagerEnumerator.cpp \
../OgreMain/src/OgreSceneNode.cpp \
../OgreMain/src/OgreSceneQuery.cpp \
../OgreMain/src/OgreScriptCompiler.cpp \
../OgreMain/src/OgreScriptLexer.cpp \
../OgreMain/src/OgreScriptParser.cpp \
../OgreMain/src/OgreScriptTranslator.cpp \
../OgreMain/src/OgreSearchOps.cpp \
../OgreMain/src/OgreSerializer.cpp \
../OgreMain/src/OgreShadowCameraSetup.cpp \
../OgreMain/src/OgreShadowCameraSetupFocused.cpp \
../OgreMain/src/OgreShadowCameraSetupLiSPSM.cpp \
../OgreMain/src/OgreShadowCameraSetupPSSM.cpp \
../OgreMain/src/OgreShadowCameraSetupPlaneOptimal.cpp \
../OgreMain/src/OgreShadowCaster.cpp \
../OgreMain/src/OgreShadowTextureManager.cpp \
../OgreMain/src/OgreShadowVolumeExtrudeProgram.cpp \
../OgreMain/src/OgreSimpleRenderable.cpp \
../OgreMain/src/OgreSimpleSpline.cpp \
../OgreMain/src/OgreSkeleton.cpp \
../OgreMain/src/OgreSkeletonInstance.cpp \
../OgreMain/src/OgreSkeletonManager.cpp \
../OgreMain/src/OgreSkeletonSerializer.cpp \
../OgreMain/src/OgreStaticGeometry.cpp \
../OgreMain/src/OgreStreamSerialiser.cpp \
../OgreMain/src/OgreString.cpp \
../OgreMain/src/OgreStringConverter.cpp \
../OgreMain/src/OgreStringInterface.cpp \
../OgreMain/src/OgreSubEntity.cpp \
../OgreMain/src/OgreSubMesh.cpp \
../OgreMain/src/OgreTagPoint.cpp \
../OgreMain/src/OgreTangentSpaceCalc.cpp \
../OgreMain/src/OgreTechnique.cpp \
../OgreMain/src/OgreTextAreaOverlayElement.cpp \
../OgreMain/src/OgreTexture.cpp \
../OgreMain/src/OgreTextureManager.cpp \
../OgreMain/src/OgreTextureUnitState.cpp \
../OgreMain/src/OgreUTFString.cpp \
../OgreMain/src/OgreUnifiedHighLevelGpuProgram.cpp \
../OgreMain/src/OgreUserObjectBindings.cpp \
../OgreMain/src/OgreVector2.cpp \
../OgreMain/src/OgreVector3.cpp \
../OgreMain/src/OgreVector4.cpp \
../OgreMain/src/OgreVertexIndexData.cpp \
../OgreMain/src/OgreViewport.cpp \
../OgreMain/src/OgreWindowEventUtilities.cpp \
../OgreMain/src/OgreWireBoundingBox.cpp \
../OgreMain/src/OgreWorkQueue.cpp \
../OgreMain/src/OgreZip.cpp 

OBJS += \
./OgreMain/src/OgreAlignedAllocator.o \
./OgreMain/src/OgreAnimable.o \
./OgreMain/src/OgreAnimation.o \
./OgreMain/src/OgreAnimationState.o \
./OgreMain/src/OgreAnimationTrack.o \
./OgreMain/src/OgreArchiveManager.o \
./OgreMain/src/OgreAutoParamDataSource.o \
./OgreMain/src/OgreAxisAlignedBox.o \
./OgreMain/src/OgreBillboard.o \
./OgreMain/src/OgreBillboardChain.o \
./OgreMain/src/OgreBillboardParticleRenderer.o \
./OgreMain/src/OgreBillboardSet.o \
./OgreMain/src/OgreBone.o \
./OgreMain/src/OgreBorderPanelOverlayElement.o \
./OgreMain/src/OgreCamera.o \
./OgreMain/src/OgreCodec.o \
./OgreMain/src/OgreColourValue.o \
./OgreMain/src/OgreCommon.o \
./OgreMain/src/OgreCompositionPass.o \
./OgreMain/src/OgreCompositionTargetPass.o \
./OgreMain/src/OgreCompositionTechnique.o \
./OgreMain/src/OgreCompositor.o \
./OgreMain/src/OgreCompositorChain.o \
./OgreMain/src/OgreCompositorInstance.o \
./OgreMain/src/OgreCompositorManager.o \
./OgreMain/src/OgreConfigFile.o \
./OgreMain/src/OgreControllerManager.o \
./OgreMain/src/OgreConvexBody.o \
./OgreMain/src/OgreDDSCodec.o \
./OgreMain/src/OgreDataStream.o \
./OgreMain/src/OgreDefaultHardwareBufferManager.o \
./OgreMain/src/OgreDefaultSceneQueries.o \
./OgreMain/src/OgreDistanceLodStrategy.o \
./OgreMain/src/OgreDynLib.o \
./OgreMain/src/OgreDynLibManager.o \
./OgreMain/src/OgreEdgeListBuilder.o \
./OgreMain/src/OgreEntity.o \
./OgreMain/src/OgreException.o \
./OgreMain/src/OgreExternalTextureSource.o \
./OgreMain/src/OgreExternalTextureSourceManager.o \
./OgreMain/src/OgreFileSystem.o \
./OgreMain/src/OgreFont.o \
./OgreMain/src/OgreFontManager.o \
./OgreMain/src/OgreFreeImageCodec.o \
./OgreMain/src/OgreFrustum.o \
./OgreMain/src/OgreGpuProgram.o \
./OgreMain/src/OgreGpuProgramManager.o \
./OgreMain/src/OgreGpuProgramParams.o \
./OgreMain/src/OgreGpuProgramUsage.o \
./OgreMain/src/OgreHardwareBufferManager.o \
./OgreMain/src/OgreHardwareIndexBuffer.o \
./OgreMain/src/OgreHardwareOcclusionQuery.o \
./OgreMain/src/OgreHardwarePixelBuffer.o \
./OgreMain/src/OgreHardwareVertexBuffer.o \
./OgreMain/src/OgreHighLevelGpuProgram.o \
./OgreMain/src/OgreHighLevelGpuProgramManager.o \
./OgreMain/src/OgreILCodecs.o \
./OgreMain/src/OgreILImageCodec.o \
./OgreMain/src/OgreILUtil.o \
./OgreMain/src/OgreImage.o \
./OgreMain/src/OgreInstancedGeometry.o \
./OgreMain/src/OgreKeyFrame.o \
./OgreMain/src/OgreLight.o \
./OgreMain/src/OgreLodStrategy.o \
./OgreMain/src/OgreLodStrategyManager.o \
./OgreMain/src/OgreLog.o \
./OgreMain/src/OgreLogManager.o \
./OgreMain/src/OgreManualObject.o \
./OgreMain/src/OgreMaterial.o \
./OgreMain/src/OgreMaterialManager.o \
./OgreMain/src/OgreMaterialSerializer.o \
./OgreMain/src/OgreMath.o \
./OgreMain/src/OgreMatrix3.o \
./OgreMain/src/OgreMatrix4.o \
./OgreMain/src/OgreMemoryAllocatedObject.o \
./OgreMain/src/OgreMemoryNedAlloc.o \
./OgreMain/src/OgreMemoryNedPooling.o \
./OgreMain/src/OgreMemoryTracker.o \
./OgreMain/src/OgreMesh.o \
./OgreMain/src/OgreMeshManager.o \
./OgreMain/src/OgreMeshSerializer.o \
./OgreMain/src/OgreMeshSerializerImpl.o \
./OgreMain/src/OgreMovableObject.o \
./OgreMain/src/OgreMovablePlane.o \
./OgreMain/src/OgreNode.o \
./OgreMain/src/OgreNumerics.o \
./OgreMain/src/OgreOptimisedUtil.o \
./OgreMain/src/OgreOptimisedUtilGeneral.o \
./OgreMain/src/OgreOptimisedUtilSSE.o \
./OgreMain/src/OgreOverlay.o \
./OgreMain/src/OgreOverlayContainer.o \
./OgreMain/src/OgreOverlayElement.o \
./OgreMain/src/OgreOverlayElementCommands.o \
./OgreMain/src/OgreOverlayElementFactory.o \
./OgreMain/src/OgreOverlayManager.o \
./OgreMain/src/OgrePVRTCCodec.o \
./OgreMain/src/OgrePanelOverlayElement.o \
./OgreMain/src/OgreParticle.o \
./OgreMain/src/OgreParticleEmitter.o \
./OgreMain/src/OgreParticleEmitterCommands.o \
./OgreMain/src/OgreParticleIterator.o \
./OgreMain/src/OgreParticleScriptCompiler.o \
./OgreMain/src/OgreParticleSystem.o \
./OgreMain/src/OgreParticleSystemManager.o \
./OgreMain/src/OgrePass.o \
./OgreMain/src/OgrePatchMesh.o \
./OgreMain/src/OgrePatchSurface.o \
./OgreMain/src/OgrePixelCountLodStrategy.o \
./OgreMain/src/OgrePixelFormat.o \
./OgreMain/src/OgrePlane.o \
./OgreMain/src/OgrePlatformInformation.o \
./OgreMain/src/OgrePolygon.o \
./OgreMain/src/OgrePose.o \
./OgreMain/src/OgrePrecompiledHeaders.o \
./OgreMain/src/OgrePredefinedControllers.o \
./OgreMain/src/OgrePrefabFactory.o \
./OgreMain/src/OgreProfiler.o \
./OgreMain/src/OgreProgressiveMesh.o \
./OgreMain/src/OgreQuaternion.o \
./OgreMain/src/OgreRectangle2D.o \
./OgreMain/src/OgreRenderQueue.o \
./OgreMain/src/OgreRenderQueueInvocation.o \
./OgreMain/src/OgreRenderQueueSortingGrouping.o \
./OgreMain/src/OgreRenderSystem.o \
./OgreMain/src/OgreRenderSystemCapabilities.o \
./OgreMain/src/OgreRenderSystemCapabilitiesManager.o \
./OgreMain/src/OgreRenderSystemCapabilitiesSerializer.o \
./OgreMain/src/OgreRenderTarget.o \
./OgreMain/src/OgreRenderTexture.o \
./OgreMain/src/OgreRenderToVertexBuffer.o \
./OgreMain/src/OgreRenderWindow.o \
./OgreMain/src/OgreResource.o \
./OgreMain/src/OgreResourceBackgroundQueue.o \
./OgreMain/src/OgreResourceGroupManager.o \
./OgreMain/src/OgreResourceManager.o \
./OgreMain/src/OgreRibbonTrail.o \
./OgreMain/src/OgreRoot.o \
./OgreMain/src/OgreRotationSpline.o \
./OgreMain/src/OgreSceneManager.o \
./OgreMain/src/OgreSceneManagerEnumerator.o \
./OgreMain/src/OgreSceneNode.o \
./OgreMain/src/OgreSceneQuery.o \
./OgreMain/src/OgreScriptCompiler.o \
./OgreMain/src/OgreScriptLexer.o \
./OgreMain/src/OgreScriptParser.o \
./OgreMain/src/OgreScriptTranslator.o \
./OgreMain/src/OgreSearchOps.o \
./OgreMain/src/OgreSerializer.o \
./OgreMain/src/OgreShadowCameraSetup.o \
./OgreMain/src/OgreShadowCameraSetupFocused.o \
./OgreMain/src/OgreShadowCameraSetupLiSPSM.o \
./OgreMain/src/OgreShadowCameraSetupPSSM.o \
./OgreMain/src/OgreShadowCameraSetupPlaneOptimal.o \
./OgreMain/src/OgreShadowCaster.o \
./OgreMain/src/OgreShadowTextureManager.o \
./OgreMain/src/OgreShadowVolumeExtrudeProgram.o \
./OgreMain/src/OgreSimpleRenderable.o \
./OgreMain/src/OgreSimpleSpline.o \
./OgreMain/src/OgreSkeleton.o \
./OgreMain/src/OgreSkeletonInstance.o \
./OgreMain/src/OgreSkeletonManager.o \
./OgreMain/src/OgreSkeletonSerializer.o \
./OgreMain/src/OgreStaticGeometry.o \
./OgreMain/src/OgreStreamSerialiser.o \
./OgreMain/src/OgreString.o \
./OgreMain/src/OgreStringConverter.o \
./OgreMain/src/OgreStringInterface.o \
./OgreMain/src/OgreSubEntity.o \
./OgreMain/src/OgreSubMesh.o \
./OgreMain/src/OgreTagPoint.o \
./OgreMain/src/OgreTangentSpaceCalc.o \
./OgreMain/src/OgreTechnique.o \
./OgreMain/src/OgreTextAreaOverlayElement.o \
./OgreMain/src/OgreTexture.o \
./OgreMain/src/OgreTextureManager.o \
./OgreMain/src/OgreTextureUnitState.o \
./OgreMain/src/OgreUTFString.o \
./OgreMain/src/OgreUnifiedHighLevelGpuProgram.o \
./OgreMain/src/OgreUserObjectBindings.o \
./OgreMain/src/OgreVector2.o \
./OgreMain/src/OgreVector3.o \
./OgreMain/src/OgreVector4.o \
./OgreMain/src/OgreVertexIndexData.o \
./OgreMain/src/OgreViewport.o \
./OgreMain/src/OgreWindowEventUtilities.o \
./OgreMain/src/OgreWireBoundingBox.o \
./OgreMain/src/OgreWorkQueue.o \
./OgreMain/src/OgreZip.o 

CPP_DEPS += \
./OgreMain/src/OgreAlignedAllocator.d \
./OgreMain/src/OgreAnimable.d \
./OgreMain/src/OgreAnimation.d \
./OgreMain/src/OgreAnimationState.d \
./OgreMain/src/OgreAnimationTrack.d \
./OgreMain/src/OgreArchiveManager.d \
./OgreMain/src/OgreAutoParamDataSource.d \
./OgreMain/src/OgreAxisAlignedBox.d \
./OgreMain/src/OgreBillboard.d \
./OgreMain/src/OgreBillboardChain.d \
./OgreMain/src/OgreBillboardParticleRenderer.d \
./OgreMain/src/OgreBillboardSet.d \
./OgreMain/src/OgreBone.d \
./OgreMain/src/OgreBorderPanelOverlayElement.d \
./OgreMain/src/OgreCamera.d \
./OgreMain/src/OgreCodec.d \
./OgreMain/src/OgreColourValue.d \
./OgreMain/src/OgreCommon.d \
./OgreMain/src/OgreCompositionPass.d \
./OgreMain/src/OgreCompositionTargetPass.d \
./OgreMain/src/OgreCompositionTechnique.d \
./OgreMain/src/OgreCompositor.d \
./OgreMain/src/OgreCompositorChain.d \
./OgreMain/src/OgreCompositorInstance.d \
./OgreMain/src/OgreCompositorManager.d \
./OgreMain/src/OgreConfigFile.d \
./OgreMain/src/OgreControllerManager.d \
./OgreMain/src/OgreConvexBody.d \
./OgreMain/src/OgreDDSCodec.d \
./OgreMain/src/OgreDataStream.d \
./OgreMain/src/OgreDefaultHardwareBufferManager.d \
./OgreMain/src/OgreDefaultSceneQueries.d \
./OgreMain/src/OgreDistanceLodStrategy.d \
./OgreMain/src/OgreDynLib.d \
./OgreMain/src/OgreDynLibManager.d \
./OgreMain/src/OgreEdgeListBuilder.d \
./OgreMain/src/OgreEntity.d \
./OgreMain/src/OgreException.d \
./OgreMain/src/OgreExternalTextureSource.d \
./OgreMain/src/OgreExternalTextureSourceManager.d \
./OgreMain/src/OgreFileSystem.d \
./OgreMain/src/OgreFont.d \
./OgreMain/src/OgreFontManager.d \
./OgreMain/src/OgreFreeImageCodec.d \
./OgreMain/src/OgreFrustum.d \
./OgreMain/src/OgreGpuProgram.d \
./OgreMain/src/OgreGpuProgramManager.d \
./OgreMain/src/OgreGpuProgramParams.d \
./OgreMain/src/OgreGpuProgramUsage.d \
./OgreMain/src/OgreHardwareBufferManager.d \
./OgreMain/src/OgreHardwareIndexBuffer.d \
./OgreMain/src/OgreHardwareOcclusionQuery.d \
./OgreMain/src/OgreHardwarePixelBuffer.d \
./OgreMain/src/OgreHardwareVertexBuffer.d \
./OgreMain/src/OgreHighLevelGpuProgram.d \
./OgreMain/src/OgreHighLevelGpuProgramManager.d \
./OgreMain/src/OgreILCodecs.d \
./OgreMain/src/OgreILImageCodec.d \
./OgreMain/src/OgreILUtil.d \
./OgreMain/src/OgreImage.d \
./OgreMain/src/OgreInstancedGeometry.d \
./OgreMain/src/OgreKeyFrame.d \
./OgreMain/src/OgreLight.d \
./OgreMain/src/OgreLodStrategy.d \
./OgreMain/src/OgreLodStrategyManager.d \
./OgreMain/src/OgreLog.d \
./OgreMain/src/OgreLogManager.d \
./OgreMain/src/OgreManualObject.d \
./OgreMain/src/OgreMaterial.d \
./OgreMain/src/OgreMaterialManager.d \
./OgreMain/src/OgreMaterialSerializer.d \
./OgreMain/src/OgreMath.d \
./OgreMain/src/OgreMatrix3.d \
./OgreMain/src/OgreMatrix4.d \
./OgreMain/src/OgreMemoryAllocatedObject.d \
./OgreMain/src/OgreMemoryNedAlloc.d \
./OgreMain/src/OgreMemoryNedPooling.d \
./OgreMain/src/OgreMemoryTracker.d \
./OgreMain/src/OgreMesh.d \
./OgreMain/src/OgreMeshManager.d \
./OgreMain/src/OgreMeshSerializer.d \
./OgreMain/src/OgreMeshSerializerImpl.d \
./OgreMain/src/OgreMovableObject.d \
./OgreMain/src/OgreMovablePlane.d \
./OgreMain/src/OgreNode.d \
./OgreMain/src/OgreNumerics.d \
./OgreMain/src/OgreOptimisedUtil.d \
./OgreMain/src/OgreOptimisedUtilGeneral.d \
./OgreMain/src/OgreOptimisedUtilSSE.d \
./OgreMain/src/OgreOverlay.d \
./OgreMain/src/OgreOverlayContainer.d \
./OgreMain/src/OgreOverlayElement.d \
./OgreMain/src/OgreOverlayElementCommands.d \
./OgreMain/src/OgreOverlayElementFactory.d \
./OgreMain/src/OgreOverlayManager.d \
./OgreMain/src/OgrePVRTCCodec.d \
./OgreMain/src/OgrePanelOverlayElement.d \
./OgreMain/src/OgreParticle.d \
./OgreMain/src/OgreParticleEmitter.d \
./OgreMain/src/OgreParticleEmitterCommands.d \
./OgreMain/src/OgreParticleIterator.d \
./OgreMain/src/OgreParticleScriptCompiler.d \
./OgreMain/src/OgreParticleSystem.d \
./OgreMain/src/OgreParticleSystemManager.d \
./OgreMain/src/OgrePass.d \
./OgreMain/src/OgrePatchMesh.d \
./OgreMain/src/OgrePatchSurface.d \
./OgreMain/src/OgrePixelCountLodStrategy.d \
./OgreMain/src/OgrePixelFormat.d \
./OgreMain/src/OgrePlane.d \
./OgreMain/src/OgrePlatformInformation.d \
./OgreMain/src/OgrePolygon.d \
./OgreMain/src/OgrePose.d \
./OgreMain/src/OgrePrecompiledHeaders.d \
./OgreMain/src/OgrePredefinedControllers.d \
./OgreMain/src/OgrePrefabFactory.d \
./OgreMain/src/OgreProfiler.d \
./OgreMain/src/OgreProgressiveMesh.d \
./OgreMain/src/OgreQuaternion.d \
./OgreMain/src/OgreRectangle2D.d \
./OgreMain/src/OgreRenderQueue.d \
./OgreMain/src/OgreRenderQueueInvocation.d \
./OgreMain/src/OgreRenderQueueSortingGrouping.d \
./OgreMain/src/OgreRenderSystem.d \
./OgreMain/src/OgreRenderSystemCapabilities.d \
./OgreMain/src/OgreRenderSystemCapabilitiesManager.d \
./OgreMain/src/OgreRenderSystemCapabilitiesSerializer.d \
./OgreMain/src/OgreRenderTarget.d \
./OgreMain/src/OgreRenderTexture.d \
./OgreMain/src/OgreRenderToVertexBuffer.d \
./OgreMain/src/OgreRenderWindow.d \
./OgreMain/src/OgreResource.d \
./OgreMain/src/OgreResourceBackgroundQueue.d \
./OgreMain/src/OgreResourceGroupManager.d \
./OgreMain/src/OgreResourceManager.d \
./OgreMain/src/OgreRibbonTrail.d \
./OgreMain/src/OgreRoot.d \
./OgreMain/src/OgreRotationSpline.d \
./OgreMain/src/OgreSceneManager.d \
./OgreMain/src/OgreSceneManagerEnumerator.d \
./OgreMain/src/OgreSceneNode.d \
./OgreMain/src/OgreSceneQuery.d \
./OgreMain/src/OgreScriptCompiler.d \
./OgreMain/src/OgreScriptLexer.d \
./OgreMain/src/OgreScriptParser.d \
./OgreMain/src/OgreScriptTranslator.d \
./OgreMain/src/OgreSearchOps.d \
./OgreMain/src/OgreSerializer.d \
./OgreMain/src/OgreShadowCameraSetup.d \
./OgreMain/src/OgreShadowCameraSetupFocused.d \
./OgreMain/src/OgreShadowCameraSetupLiSPSM.d \
./OgreMain/src/OgreShadowCameraSetupPSSM.d \
./OgreMain/src/OgreShadowCameraSetupPlaneOptimal.d \
./OgreMain/src/OgreShadowCaster.d \
./OgreMain/src/OgreShadowTextureManager.d \
./OgreMain/src/OgreShadowVolumeExtrudeProgram.d \
./OgreMain/src/OgreSimpleRenderable.d \
./OgreMain/src/OgreSimpleSpline.d \
./OgreMain/src/OgreSkeleton.d \
./OgreMain/src/OgreSkeletonInstance.d \
./OgreMain/src/OgreSkeletonManager.d \
./OgreMain/src/OgreSkeletonSerializer.d \
./OgreMain/src/OgreStaticGeometry.d \
./OgreMain/src/OgreStreamSerialiser.d \
./OgreMain/src/OgreString.d \
./OgreMain/src/OgreStringConverter.d \
./OgreMain/src/OgreStringInterface.d \
./OgreMain/src/OgreSubEntity.d \
./OgreMain/src/OgreSubMesh.d \
./OgreMain/src/OgreTagPoint.d \
./OgreMain/src/OgreTangentSpaceCalc.d \
./OgreMain/src/OgreTechnique.d \
./OgreMain/src/OgreTextAreaOverlayElement.d \
./OgreMain/src/OgreTexture.d \
./OgreMain/src/OgreTextureManager.d \
./OgreMain/src/OgreTextureUnitState.d \
./OgreMain/src/OgreUTFString.d \
./OgreMain/src/OgreUnifiedHighLevelGpuProgram.d \
./OgreMain/src/OgreUserObjectBindings.d \
./OgreMain/src/OgreVector2.d \
./OgreMain/src/OgreVector3.d \
./OgreMain/src/OgreVector4.d \
./OgreMain/src/OgreVertexIndexData.d \
./OgreMain/src/OgreViewport.d \
./OgreMain/src/OgreWindowEventUtilities.d \
./OgreMain/src/OgreWireBoundingBox.d \
./OgreMain/src/OgreWorkQueue.d \
./OgreMain/src/OgreZip.d 


# Each subdirectory must supply rules for building sources it contributes
OgreMain/src/%.o: ../OgreMain/src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -DUSE_GLUT -DXN_SSE -I/usr/include/ni -I/usr/lib -I/usr/include/ni/Linux-x86 -I/usr/include/nite -I/usr/include/OGRE -I/usr/include/OIS -O0 -g3 -Wall -msse3 -mssse3  -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


